server:
  port: 9090

spring:
  application:
    # 服务名称尽量用-中划线，不要用_下划线和特殊字符
    name: user-center
  # nacos 地址
  cloud:
    nacos:
      discovery:
        server-addr: ${REMOTE-SERVER-IP:127.0.0.1}:8848
#        namespace: 8d4804ec-fbe6-4f5b-beb1-64e934a44ec4
        cluster-name: BJ
        metadata:
          version: v1
    # sentinel 控制台已经上云，访问不到本地，暂时不连接
#    sentinel:
#      transport:
#        # 指定 sentinel 控制台地址
#        dashboard: ${REMOTE-SERVER-IP:127.0.0.1}:18080

  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${REMOTE-SERVER-IP:127.0.0.1}:3306/user_center?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ${REMOTE-USER-NAME}
    password: ${REMOTE-PASS-WORD}

# rocketmq
rocketmq:
  name-server: ${REMOTE-SERVER-IP:127.0.0.1}:9876