server:
  port: 9090

spring:
  application:
    # 服务名称尽量用-中划线，不要用_下划线和特殊字符
    name: user-center
  # nacos 地址
  cloud:
    nacos:
      discovery:
        server-addr: ${REMOTE-SERVER-IP:127.0.0.1}:8848
#        namespace: 8d4804ec-fbe6-4f5b-beb1-64e934a44ec4
        cluster-name: BJ
        metadata:
          version: v1
    stream:
      rocketmq:
        binder:
          name-server: ${REMOTE-SERVER-IP:127.0.0.1}:9876
      bindings:
        input:
          # 指定读取的topic
          destination: stream-test-topic
          # rocketmq的这个group必须配置，其他类型的mq可以不配置
          group: consumer-spring-cloud-stream-test
        my_input:
          # 指定读取的topic
          destination: stream-test-my-topic
          group: consumer-spring-cloud-stream-my-sink-test
    # sentinel 控制台已经上云，访问不到本地，暂时不连接
#    sentinel:
#      transport:
#        # 指定 sentinel 控制台地址
#        dashboard: ${REMOTE-SERVER-IP:127.0.0.1}:18080

  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${REMOTE-SERVER-IP:127.0.0.1}:3306/user_center?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ${REMOTE-USER-NAME}
    password: ${REMOTE-PASS-WORD}

  zipkin:
    base-url: http://${REMOTE-SERVER-IP:127.0.0.1}:9411
  sleuth:
    sampler:
      # 抽样率，默认值是 0.1 (10%)
      probability: 1.0


# rocketmq
rocketmq:
  name-server: ${REMOTE-SERVER-IP:127.0.0.1}:9876